## Manipulating Data

In [2]:
import pandas as pd

In [38]:
car_sales = pd.read_csv("car-sales (1).csv")

In [4]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [5]:
car_sales["Make"].str.lower()

0    toyota
1     honda
2    toyota
3       bmw
4    nissan
5    toyota
6     honda
7     honda
8    toyota
9    nissan
Name: Make, dtype: str

In [6]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [7]:
car_sales["Make"] = car_sales["Make"].str.lower()

In [8]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  toyota  White         150043      4   $4,000.00
1   honda    Red          87899      4   $5,000.00
2  toyota   Blue          32549      3   $7,000.00
3     bmw  Black          11179      5  $22,000.00
4  nissan  White         213095      4   $3,500.00
5  toyota  Green          99213      4   $4,500.00
6   honda   Blue          45698      4   $7,500.00
7   honda   Blue          54738      4   $7,000.00
8  toyota  White          60000      4   $6,250.00
9  nissan  White          31600      4   $9,700.00

In [11]:
car_sales_missing = pd.read_csv("car-sales-missing-data.csv")

In [12]:
car_sales_missing

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

In [13]:
car_sales_missing["Odometer"].mean()

np.float64(92302.66666666667)

In [14]:
car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean())

0    150043.000000
1     87899.000000
2     92302.666667
3     11179.000000
4    213095.000000
5     92302.666667
6     92302.666667
7     92302.666667
8     60000.000000
9     31600.000000
Name: Odometer, dtype: float64

In [15]:
car_sales_missing

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

In [16]:
car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean(),
                                     inplace=True)

## DataFrame.method(inplace=True) → usually fine.
## DataFrame["column"].method(inplace=True) → can trigger chained assignment warnings.

C:\Users\DEEPAK SINGH\AppData\Local\Temp\ipykernel_11708\2846786116.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean(),

0    150043.000000
1     87899.000000
2     92302.666667
3     11179.000000
4    213095.000000
5     92302.666667
6     92302.666667
7     92302.666667
8     60000.000000
9     31600.000000
Name: Odometer, dtype: float64

In [17]:
car_sales_missing["Odometer"] = car_sales_missing["Odometer"].fillna(
    car_sales_missing["Odometer"].mean()
)

In [18]:
car_sales_missing

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500
6   Honda    NaN   92302.666667    4.0   $7,500
7   Honda   Blue   92302.666667    4.0      NaN
8  Toyota  White   60000.000000    NaN      NaN
9     NaN  White   31600.000000    4.0   $9,700

In [19]:
car_sales_missing.dropna()

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500

In [21]:

car_sales_missing.dropna(inplace=True)
car_sales_missing

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500

In [24]:
car_sales_missing = pd.read_csv("car-sales-missing-data.csv")
car_sales_missing

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

In [29]:
car_sales_missing_dropped = car_sales_missing.dropna()
car_sales_missing_dropped

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500

In [30]:
car_sales_missing_dropped.to_csv("car-sales-missing-deopped.csv")

In [31]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  toyota  White         150043      4   $4,000.00
1   honda    Red          87899      4   $5,000.00
2  toyota   Blue          32549      3   $7,000.00
3     bmw  Black          11179      5  $22,000.00
4  nissan  White         213095      4   $3,500.00
5  toyota  Green          99213      4   $4,500.00
6   honda   Blue          45698      4   $7,500.00
7   honda   Blue          54738      4   $7,000.00
8  toyota  White          60000      4   $6,250.00
9  nissan  White          31600      4   $9,700.00

In [40]:
# Column for series
seats_column = pd.Series([5,5,5,5,5])

# New column called seats 
car_sales["Seats"] = seats_column
car_sales

     Make Colour  Odometer (KM)  Doors       Price  Seats
0  Toyota  White         150043      4   $4,000.00    5.0
1   Honda    Red          87899      4   $5,000.00    5.0
2  Toyota   Blue          32549      3   $7,000.00    5.0
3     BMW  Black          11179      5  $22,000.00    5.0
4  Nissan  White         213095      4   $3,500.00    5.0
5  Toyota  Green          99213      4   $4,500.00    NaN
6   Honda   Blue          45698      4   $7,500.00    NaN
7   Honda   Blue          54738      4   $7,000.00    NaN
8  Toyota  White          60000      4   $6,250.00    NaN
9  Nissan  White          31600      4   $9,700.00    NaN

In [41]:
car_sales["Seats"] = car_sales["Seats"].fillna(5)
car_sales

     Make Colour  Odometer (KM)  Doors       Price  Seats
0  Toyota  White         150043      4   $4,000.00    5.0
1   Honda    Red          87899      4   $5,000.00    5.0
2  Toyota   Blue          32549      3   $7,000.00    5.0
3     BMW  Black          11179      5  $22,000.00    5.0
4  Nissan  White         213095      4   $3,500.00    5.0
5  Toyota  Green          99213      4   $4,500.00    5.0
6   Honda   Blue          45698      4   $7,500.00    5.0
7   Honda   Blue          54738      4   $7,000.00    5.0
8  Toyota  White          60000      4   $6,250.00    5.0
9  Nissan  White          31600      4   $9,700.00    5.0

In [39]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [42]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price  Seats
0  Toyota  White         150043      4   $4,000.00    5.0
1   Honda    Red          87899      4   $5,000.00    5.0
2  Toyota   Blue          32549      3   $7,000.00    5.0
3     BMW  Black          11179      5  $22,000.00    5.0
4  Nissan  White         213095      4   $3,500.00    5.0
5  Toyota  Green          99213      4   $4,500.00    5.0
6   Honda   Blue          45698      4   $7,500.00    5.0
7   Honda   Blue          54738      4   $7,000.00    5.0
8  Toyota  White          60000      4   $6,250.00    5.0
9  Nissan  White          31600      4   $9,700.00    5.0

In [44]:
# Column from Python List 
fuel_economy = [7.5, 9.2, 5.0, 9.6, 8.7, 4.7, 7.6, 8.7, 3.0, 4.5]
car_sales["fuel per 100km"] = fuel_economy
car_sales

     Make Colour  Odometer (KM)  Doors       Price  Seats  fuel per 100km
0  Toyota  White         150043      4   $4,000.00    7.5             7.5
1   Honda    Red          87899      4   $5,000.00    9.2             9.2
2  Toyota   Blue          32549      3   $7,000.00    5.0             5.0
3     BMW  Black          11179      5  $22,000.00    9.6             9.6
4  Nissan  White         213095      4   $3,500.00    8.7             8.7
5  Toyota  Green          99213      4   $4,500.00    4.7             4.7
6   Honda   Blue          45698      4   $7,500.00    7.6             7.6
7   Honda   Blue          54738      4   $7,000.00    8.7             8.7
8  Toyota  White          60000      4   $6,250.00    3.0             3.0
9  Nissan  White          31600      4   $9,700.00    4.5             4.5

In [55]:
car_sales["Total fuel used (L)"] = car_sales["Odometer (KM)"]/100 * car_sales["fuel per 100km"]

In [56]:
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Seats,fuel per 100km,Number of wheels,Passed road saftey,Total fuel used (L)
0,Toyota,White,150043,4,"$4,000.00",7.5,7.5,4,True,11253.225
1,Honda,Red,87899,4,"$5,000.00",9.2,9.2,4,True,8086.708
2,Toyota,Blue,32549,3,"$7,000.00",5.0,5.0,4,True,1627.450
3,BMW,Black,11179,5,"$22,000.00",9.6,9.6,4,True,1073.184
4,Nissan,White,213095,4,"$3,500.00",8.7,8.7,4,True,18539.265
5,Toyota,Green,99213,4,"$4,500.00",4.7,4.7,4,True,4663.011
6,Honda,Blue,45698,4,"$7,500.00",7.6,7.6,4,True,3473.048
7,Honda,Blue,54738,4,"$7,000.00",8.7,8.7,4,True,4762.206
8,Toyota,White,60000,4,"$6,250.00",3.0,3.0,4,True,1800.000
9,Nissan,White,31600,4,"$9,700.00",4.5,4.5,4,True,1422.000

In [57]:
# Create a column from a single value
car_sales["Number of wheels"] = 4
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Seats,fuel per 100km,Number of wheels,Passed road saftey,Total fuel used (L)
0,Toyota,White,150043,4,"$4,000.00",7.5,7.5,4,True,11253.225
1,Honda,Red,87899,4,"$5,000.00",9.2,9.2,4,True,8086.708
2,Toyota,Blue,32549,3,"$7,000.00",5.0,5.0,4,True,1627.450
3,BMW,Black,11179,5,"$22,000.00",9.6,9.6,4,True,1073.184
4,Nissan,White,213095,4,"$3,500.00",8.7,8.7,4,True,18539.265
5,Toyota,Green,99213,4,"$4,500.00",4.7,4.7,4,True,4663.011
6,Honda,Blue,45698,4,"$7,500.00",7.6,7.6,4,True,3473.048
7,Honda,Blue,54738,4,"$7,000.00",8.7,8.7,4,True,4762.206
8,Toyota,White,60000,4,"$6,250.00",3.0,3.0,4,True,1800.000
9,Nissan,White,31600,4,"$9,700.00",4.5,4.5,4,True,1422.000

In [58]:
car_sales["Passed road saftey"] = True
car_sales.dtypes

Make                       str
Colour                     str
Odometer (KM)            int64
Doors                    int64
Price                      str
Seats                  float64
fuel per 100km         float64
Number of wheels         int64
Passed road saftey        bool
Total fuel used (L)    float64
dtype: object

In [59]:
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Seats,fuel per 100km,Number of wheels,Passed road saftey,Total fuel used (L)
0,Toyota,White,150043,4,"$4,000.00",7.5,7.5,4,True,11253.225
1,Honda,Red,87899,4,"$5,000.00",9.2,9.2,4,True,8086.708
2,Toyota,Blue,32549,3,"$7,000.00",5.0,5.0,4,True,1627.450
3,BMW,Black,11179,5,"$22,000.00",9.6,9.6,4,True,1073.184
4,Nissan,White,213095,4,"$3,500.00",8.7,8.7,4,True,18539.265
5,Toyota,Green,99213,4,"$4,500.00",4.7,4.7,4,True,4663.011
6,Honda,Blue,45698,4,"$7,500.00",7.6,7.6,4,True,3473.048
7,Honda,Blue,54738,4,"$7,000.00",8.7,8.7,4,True,4762.206
8,Toyota,White,60000,4,"$6,250.00",3.0,3.0,4,True,1800.000
9,Nissan,White,31600,4,"$9,700.00",4.5,4.5,4,True,1422.000

In [61]:
# Drop a particular column
car_sales = car_sales.drop("Total fuel used (L)", axis = 1)
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Seats,fuel per 100km,Number of wheels,Passed road saftey
0,Toyota,White,150043,4,"$4,000.00",7.5,7.5,4,True
1,Honda,Red,87899,4,"$5,000.00",9.2,9.2,4,True
2,Toyota,Blue,32549,3,"$7,000.00",5.0,5.0,4,True
3,BMW,Black,11179,5,"$22,000.00",9.6,9.6,4,True
4,Nissan,White,213095,4,"$3,500.00",8.7,8.7,4,True
5,Toyota,Green,99213,4,"$4,500.00",4.7,4.7,4,True
6,Honda,Blue,45698,4,"$7,500.00",7.6,7.6,4,True
7,Honda,Blue,54738,4,"$7,000.00",8.7,8.7,4,True
8,Toyota,White,60000,4,"$6,250.00",3.0,3.0,4,True
9,Nissan,White,31600,4,"$9,700.00",4.5,4.5,4,True

In [62]:
car_sales_shuffled = car_sales.sample(frac=1)
car_sales_shuffled

,Make,Colour,Odometer (KM),Doors,Price,Seats,fuel per 100km,Number of wheels,Passed road saftey
4,Nissan,White,213095,4,"$3,500.00",8.7,8.7,4,True
9,Nissan,White,31600,4,"$9,700.00",4.5,4.5,4,True
2,Toyota,Blue,32549,3,"$7,000.00",5.0,5.0,4,True
7,Honda,Blue,54738,4,"$7,000.00",8.7,8.7,4,True
5,Toyota,Green,99213,4,"$4,500.00",4.7,4.7,4,True
8,Toyota,White,60000,4,"$6,250.00",3.0,3.0,4,True
3,BMW,Black,11179,5,"$22,000.00",9.6,9.6,4,True
0,Toyota,White,150043,4,"$4,000.00",7.5,7.5,4,True
1,Honda,Red,87899,4,"$5,000.00",9.2,9.2,4,True
6,Honda,Blue,45698,4,"$7,500.00",7.6,7.6,4,True

In [63]:
# Only select 20% of data
car_sales_shuffled.sample(frac=0.01)

Empty DataFrame
Columns: [Make, Colour, Odometer (KM), Doors, Price, Seats, fuel per 100km, Number of wheels, Passed road saftey]
Index: []

In [64]:
car_sales_shuffled.reset_index(drop=True, inplace=True)
car_sales_shuffled

,Make,Colour,Odometer (KM),Doors,Price,Seats,fuel per 100km,Number of wheels,Passed road saftey
0,Nissan,White,213095,4,"$3,500.00",8.7,8.7,4,True
1,Nissan,White,31600,4,"$9,700.00",4.5,4.5,4,True
2,Toyota,Blue,32549,3,"$7,000.00",5.0,5.0,4,True
3,Honda,Blue,54738,4,"$7,000.00",8.7,8.7,4,True
4,Toyota,Green,99213,4,"$4,500.00",4.7,4.7,4,True
5,Toyota,White,60000,4,"$6,250.00",3.0,3.0,4,True
6,BMW,Black,11179,5,"$22,000.00",9.6,9.6,4,True
7,Toyota,White,150043,4,"$4,000.00",7.5,7.5,4,True
8,Honda,Red,87899,4,"$5,000.00",9.2,9.2,4,True
9,Honda,Blue,45698,4,"$7,500.00",7.6,7.6,4,True

In [65]:
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Seats,fuel per 100km,Number of wheels,Passed road saftey
0,Toyota,White,150043,4,"$4,000.00",7.5,7.5,4,True
1,Honda,Red,87899,4,"$5,000.00",9.2,9.2,4,True
2,Toyota,Blue,32549,3,"$7,000.00",5.0,5.0,4,True
3,BMW,Black,11179,5,"$22,000.00",9.6,9.6,4,True
4,Nissan,White,213095,4,"$3,500.00",8.7,8.7,4,True
5,Toyota,Green,99213,4,"$4,500.00",4.7,4.7,4,True
6,Honda,Blue,45698,4,"$7,500.00",7.6,7.6,4,True
7,Honda,Blue,54738,4,"$7,000.00",8.7,8.7,4,True
8,Toyota,White,60000,4,"$6,250.00",3.0,3.0,4,True
9,Nissan,White,31600,4,"$9,700.00",4.5,4.5,4,True

In [66]:
car_sales["Odometer (KM)"] = car_sales["Odometer (KM)"].apply(lambda x: x / 1.6)
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Seats,fuel per 100km,Number of wheels,Passed road saftey
0,Toyota,White,93776.875,4,"$4,000.00",7.5,7.5,4,True
1,Honda,Red,54936.875,4,"$5,000.00",9.2,9.2,4,True
2,Toyota,Blue,20343.125,3,"$7,000.00",5.0,5.0,4,True
3,BMW,Black,6986.875,5,"$22,000.00",9.6,9.6,4,True
4,Nissan,White,133184.375,4,"$3,500.00",8.7,8.7,4,True
5,Toyota,Green,62008.125,4,"$4,500.00",4.7,4.7,4,True
6,Honda,Blue,28561.250,4,"$7,500.00",7.6,7.6,4,True
7,Honda,Blue,34211.250,4,"$7,000.00",8.7,8.7,4,True
8,Toyota,White,37500.000,4,"$6,250.00",3.0,3.0,4,True
9,Nissan,White,19750.000,4,"$9,700.00",4.5,4.5,4,True

In [ ]:
# END