## Dot product exmaple (nut butter sales)

In [4]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [5]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

       Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [6]:
# Create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [7]:

prices.shape

(3,)

In [8]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index=["Price"],
                             columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

       Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [9]:

prices.shape

(3,)

In [10]:
sales_amounts.shape

(5, 3)

In [11]:
total_sales = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [12]:
# Shape aren't aligned, let's transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [13]:

# Create daily_sales
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [14]:
weekly_sales.T.shape

(3, 5)

In [15]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales.shape

(1, 5)

In [16]:
weekly_sales.shape

(5, 3)

In [17]:

weekly_sales

       Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [18]:
# Doesn't work, not the right shape
weekly_sales["Total ($)"] = daily_sales
weekly_sales

ValueError: Cannot set a DataFrame with multiple columns to the single column Total ($)

In [19]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

       Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

## Comparison Operators

In [20]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [21]:
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[10,11,12], [13,14,15],[16,17,18]]])

In [22]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [23]:

a1 > a2

array([[False, False, False],
       [False, False, False]])

In [24]:

bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [25]:

type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [28]:
a1 > 5

array([False, False, False])

In [27]:
a1 < 5

array([ True,  True,  True])

In [29]:

a1 == a1

array([ True,  True,  True])

In [30]:
a1

array([1, 2, 3])

In [31]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [32]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

## 5. Sorting arrays

In [33]:

random_array = np.random.randint(10, size=(3, 5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]], dtype=int32)

In [34]:

random_array.shape

(3, 5)

In [35]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]], dtype=int32)

In [36]:

random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]], dtype=int32)

In [37]:

np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]])

In [38]:
a1

array([1, 2, 3])

In [39]:
np.argsort(a1)

array([0, 1, 2])

In [40]:

random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]], dtype=int32)

In [41]:
np.argmax(random_array, axis=0)

array([1, 1, 1, 0, 0])

In [42]:

np.argmax(random_array, axis=1)

array([4, 1, 1])

## 6. Practical Example - NumPy in Action!!!!

In [51]:
# Turn an image into a NumPy array
from matplotlib.image import imread

panda = imread("D:\images.jfif")

print(type(panda))
print(panda.shape)

<class 'numpy.ndarray'>
(259, 194, 3)

<>:4: SyntaxWarning: "\i" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\i"? A raw string is also an option.
<>:4: SyntaxWarning: "\i" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\i"? A raw string is also an option.
C:\Users\DEEPAK SINGH\AppData\Local\Temp\ipykernel_13452\453157464.py:4: SyntaxWarning: "\i" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\i"? A raw string is also an option.
  panda = imread("D:\images.jfif")

In [52]:
panda.size, panda.shape, panda.ndim

(150738, (259, 194, 3), 3)

In [53]:
panda

array([[[ 90,  71,  64],
        [ 98,  79,  72],
        [107,  90,  82],
        ...,
        [ 79,  70,  65],
        [ 84,  71,  62],
        [ 84,  71,  62]],

       [[106,  87,  80],
        [108,  89,  82],
        [105,  88,  80],
        ...,
        [ 79,  70,  65],
        [ 77,  64,  55],
        [ 77,  64,  55]],

       [[118,  99,  92],
        [115,  96,  89],
        [103,  86,  78],
        ...,
        [ 92,  81,  75],
        [ 80,  66,  57],
        [ 79,  65,  56]],

       ...,

       [[ 37,  60,  31],
        [ 46,  71,  41],
        [ 57,  82,  52],
        ...,
        [ 22,  41,  22],
        [ 25,  49,  15],
        [ 26,  50,  16]],

       [[ 25,  48,  19],
        [ 36,  61,  31],
        [ 51,  76,  46],
        ...,
        [ 20,  39,  20],
        [ 20,  44,   8],
        [ 20,  44,   8]],

       [[ 11,  34,   5],
        [ 24,  49,  19],
        [ 43,  68,  38],
        ...,
        [ 17,  36,  17],
        [ 14,  39,   0],
        [ 15,  40,   1]]], shape=(259, 194, 3), dtype=uint8)

SyntaxError: invalid syntax (2084924934.py, line 1)